# -*- coding: utf-8 -*-
"""UAS_Prak_G.211.22.0100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQrQTaP6u0KDoW3w0_yuRFTai3ARdosl
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Membaca file CSV
data_stock = pd.read_csv('stock.csv', sep=';')
print(data_stock.head(13))  # Menampilkan 13 data yang ada dalam file stock.csv

"""**A. Distribusi data pada setiap atribut Purchase Price, Current Price dan Gain/Loss dengan
grafik histogram**
"""

# Menampilkan histogram untuk atribut "Purchase Price" menggunakan Seaborn
plt.figure(figsize=(20, 4))
sns.histplot(data=data_stock, x='Purchase Price', kde=True, edgecolor='white', color='yellow')
plt.xlabel('Purchase Price')
plt.ylabel('Count')
plt.title('Histogram of Purchase Price')
plt.show()

# Menampilkan histogram untuk atribut "Current Price" menggunakan Seaborn
plt.figure(figsize=(20, 4))
sns.histplot(data=data_stock, x='Current Price', kde=True, edgecolor='white', color='yellow')
plt.xlabel('Current Price')
plt.ylabel('Count')
plt.title('Histogram of Current Price')
plt.show()

# Menampilkan histogram untuk atribut "Gain/Loss" menggunakan Seaborn
plt.figure(figsize=(20, 4))
sns.histplot(data=data_stock, x='Gain/Loss', kde=True, edgecolor='white', color='yellow')
plt.xlabel('Gain/Loss')
plt.ylabel('Count')
plt.title('Histogram of Gain/Loss')
plt.show()

"""**B. Atribut Stock Name dan Symbol yang memiliki Dividen / Share 5 tertinggi**"""

# Mengurutkan data berdasarkan kolom "Dividen/Share" secara menurun
data_stock_dividendShare = data_stock.sort_values('Dividend/Share', ascending=False)

# Mengambil 5 baris teratas
top_5_dividends = data_stock_dividendShare.head(5)[['Stock Name', 'Symbol', 'Dividend/Share']]

# Menampilkan hasil, 5 data
print("Atribut Stock Name dan Symbol dengan Dividen/Share 5 tertinggi:")
print(top_5_dividends)

"""**C. Atribut Stock Name dan Symbol yang memiliki Market Value 5 tertinggi**"""

# Mengurutkan data berdasarkan kolom "Market Value" secara menurun
data_stock_marketValue = data_stock.sort_values('Market Value', ascending=False)

# Mengambil 5 baris teratas
top_5_market_values = data_stock_marketValue.head(5)[['Stock Name', 'Symbol', 'Market Value']]

# Menampilkan hasil, 5 data
print("Atribut Stock Name dan Symbol dengan Market Value 5 tertinggi:")
print(top_5_market_values)

"""**D. Atribut Stock Name dan Symbol yang memiliki Annual Yield 7 tertinggi**"""

# Mengurutkan data berdasarkan kolom "Annual Yield" secara menurun
data_stock_annualYield = data_stock.sort_values('Annual Yield', ascending=False)

# Mengambil 7 baris teratas
top_7_annual_yields = data_stock_annualYield.head(7)[['Stock Name', 'Symbol', 'Annual Yield']]

# Menampilkan hasil, 7 data
print("Atribut Stock Name dan Symbol dengan Annual Yield 7 tertinggi:")
print(top_7_annual_yields)